---
title: "NMDS Demo"
author: "Ted Flynn"
date: "2024-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(knitr)))
suppressWarnings(suppressMessages(library(lubridate)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(vegan)))
suppressWarnings(suppressMessages(library(janitor)))
suppressWarnings(suppressMessages(library(here)))

```

## Import Data
This uses phytoplankton data from the FASTR project to create NMDS plots. 

```{r import, echo=FALSE, message=FALSE}

load(file = here("NMDS-demo","df_phyto_FASTR_gen_BV.RData"))

# Remove extra unrelated columns
df_phyto_FASTR_gen_BV <- df_phyto_FASTR_gen_BV %>% 
  select(!Group:Type)

```

##

```{r process data}

# Use set.seed to make distance matrix calculations reproducible
set.seed(2390)

# Pull out yearly data b/c we will be calculating each year separately
years <- unique(df_phyto_FASTR_gen_BV$Year) 
years <- sort(years, decreasing = F, na.last = T)

# Create blank data frame to fill stresses in
stresses <- data.frame(Year = years, stress = NA)
ls_dfs <- list()

# Generate NMDS data with metaMDS by each year separately
for (i in 1:length(years)) {
  genw <- pivot_wider(df_phyto_FASTR_gen_BV, 
                      names_from = "Genus", 
                      values_from = "BV.um3.per.mL",
                      values_fill = 0)
  
  genw <- genw %>%
    filter(Year == years[i])
  
  # Calculate the nMDS using vegan 
  phyto.NMDS <- metaMDS(comm = genw[c(7:139)],
                        distance = "bray",
                        k = 3,
                        trymax = 500
  )
  
  stresses$stress[which(stresses$Year == years[i])] <- phyto.NMDS$stress
  
  #look at Shepard plot which shows scatter around the regression between the interpoint distances 
  #in the final configuration (i.e., the distances between each pair of communities) against their 
  #original dissimilarities.
  stressplot(phyto.NMDS)
  
  # Using the scores function from vegan to extract the site scores and convert to a data.frame
  data.scores <- as_tibble(scores(phyto.NMDS, display = "sites"))
  
  # Combine metadata with NMDS data scores to plot in ggplot
  meta <- genw %>% select(1:6)
  meta <- cbind(meta, data.scores)
  
  # Read in years as a character otherwise it shows up as a number and gets displayed as a gradient
  meta$Year <- as.character(meta$Year)
  
  ls_dfs[[i]] <- meta
  
}

df_phyto_NMDS <- do.call(rbind, ls_dfs)

# Output stresses for us in plotting NMDS
write_csv(stresses, file = here("NMDS-demo","NMDS_stress.csv"))

```

## Plot NMDS Using ggplot2

You can also embed plots, for example:

```{r pressure, echo=FALSE}

# Set location to save plots
plots <- here("NMDS-demo")

# Create a ggplot2 theme for the NMDS plots organized by region
theme_update(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.border = element_rect(fill = NA, colour = "black"),
    strip.background = element_rect(fill = "gray", colour = "black"),
    legend.position = "bottom",
    legend.key = element_rect(fill = "white", colour = NA)
    )

p_NMDS_region <- ggplot(df_phyto_NMDS,
                        aes(x = NMDS1, y = NMDS2, fill = Region)) +
  geom_point(size = 3,
             pch = 21,
             color = "black") +
  stat_ellipse(aes(color = Region)) + 
  labs(color = "Region",
       x = NULL,
       y = NULL)

p_NMDS_region +
  facet_wrap(Year ~ ., ncol = 3, dir = "h") +
  scale_fill_brewer(palette = "Set1") +
  scale_color_brewer(palette = "Set1")

ggsave(path = plots,
       filename = "phyto_NMDS_by_region.png", 
       device = "png",
       scale=1.0, 
       units="in",
       height=4.5,
       width=5.5, 
       dpi="print")

```


